### ISSUE TITLE
Does not work with pyinstaller

### ISSUE THREAD

**Issue by TimZwart** [mrmaxguns/wonderwordsmodule#26]
I have a project in which I'm using wonderwords. I decided to use pyinstaller to create an executable. Only it complains about not being able to find a temporary text file it can't find. On windows 10. I'm probably going to implement my own bad version of this package for my specific user case but I thought I'd let you know.

**Comment by mrmaxguns** [comment]
Would you mind sharing the error message?

**Comment by Py-Kat** [comment]
I experienced the same issue when building an executable containing wonderwords with PyInstaller. It appears this can be resolved by adding `--collect-data wonderwords` to the PyInstaller command. This will bundle the previously missing text files with the executable.

When building without the `--collect-data` option, running the executable will result in a `FileNotFoundError` when the class methods attempt to access internal .txt files used by wonderwords.

This behavior was confirmed on `wonderwords 2.2.0` and `wonderwords 3.0.1`.

# Example

*Code snippet used for tests*
```
# main.py

from wonderwords import RandomWord
words = RandomWord()
print(words.word())
```

## Built using `--collect-data`

### PyInstaller command
`pyinstaller --collect-data wonderwords -n wondertest main.py`

### Executable output
```
developmental
```

## Built WITHOUT using `--collect-data`

### PyInstaller command
`pyinstaller -n wondertest main.py`

### Executable output
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from wonderwords import RandomWord
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "pyimod02_importers.py", line 457, in exec_module
  File "wonderwords\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "pyimod02_importers.py", line 457, in exec_module
  File "wonderwords\random_word.py", line 70, in <module>
  File "wonderwords\random_word.py", line 58, in _load_default_categories
  File "wonderwords\random_word.py", line 66, in _get_words_from_text_file
  File "importlib\resources\_functional.py", line 20, in open_text
  File "pathlib\__init__.py", line 771, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\...\\dist\\wondertest\\_internal\\wonderwords\\assets\\nounlist.txt'
[PYI-29232:ERROR] Failed to execute script 'main' due to unhandled exception!
```

# Python and package versions when tested
- `python 3.14.3`
- `wonderwords 2.2.0 and 3.0.1`
- `pyinstaller 6.19.0`
