### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by mrmaxguns** [mrmaxguns/wonderwordsmodule#3]
After importing the package and using random_word() python gives the following error:
```python
>>> from wonderwords import random_word
>>> my_words = random_word.random_word()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/wonderwords/random_word.py", line 9, in __init__
    word_file = open('words.txt', "r")
FileNotFoundError: [Errno 2] No such file or directory: 'words.txt'
```
I have checked to see if the file is in the same directory as the python file, and it is. This shouldn't happen as when a user installs the package, they will get this error.
Both files are located in:
```
/usr/local/lib/python3.7/site-packages/wonderwords
```

**Comment by mrmaxguns** [comment]
Solved using importlib_resources
