### ISSUE TITLE
Seems to need rich but not in the requirements

### ISSUE THREAD

**Issue by charlieh0tel** [mrmaxguns/wonderwordsmodule#37]
**Describe the bug**
Module seems to require rich but pip does not know that.

**To Reproduce**

```
(test) ch@shoe: $ wonderwords -l 3 -p noun -d -
-bash: wonderwords: command not found
(test) ch@shoe: $ pip install wonderwords
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting wonderwords
  Using cached https://www.piwheels.org/simple/wonderwords/wonderwords-2.2.0-py3-none-any.whl (44 kB)
Installing collected packages: wonderwords
Successfully installed wonderwords-2.2.0
(test) ch@shoe: $ wonderwords -l 3 -p noun -d -
Traceback (most recent call last):
  File "/home/ch/src/meshtastic-native/bin/wonderwords", line 5, in <module>
    from wonderwords.cmdline_parser import main
  File "/home/ch/src/meshtastic-native/lib/python3.11/site-packages/wonderwords/cmdline_parser.py", line 5, in <module>
    from .cmdline import WonderwordsCommandLine
  File "/home/ch/src/meshtastic-native/lib/python3.11/site-packages/wonderwords/cmdline.py", line 1, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'
(test) ch@shoe: $ pip install rich
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting rich
  Using cached https://www.piwheels.org/simple/rich/rich-13.9.2-py3-none-any.whl (242 kB)
Collecting markdown-it-py>=2.2.0
  Using cached https://www.piwheels.org/simple/markdown-it-py/markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Collecting pygments<3.0.0,>=2.13.0
  Using cached https://www.piwheels.org/simple/pygments/pygments-2.18.0-py3-none-any.whl (1.2 MB)
Collecting mdurl~=0.1
  Using cached https://www.piwheels.org/simple/mdurl/mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pygments, mdurl, markdown-it-py, rich
Successfully installed markdown-it-py-3.0.0 mdurl-0.1.2 pygments-2.18.0 rich-13.9.2
(test) ch@shoe: $ wonderwords -l 3 -p noun -d -
organizing-illustration-nursing
(test) ch@shoe: $ 

```

**Expected behavior**
rich in requirements

** OS **
 - OS: Debian Bookworm

**Comment by xelandernt** [comment]
You need to install wonderwords with the `cli` dependency group.

Try:
```
pip install "wonderwords[cli]"
```
